cfg: !!python/object:__main__.Config
  data: !!python/object:__main__.DataConfig
    batch_size: 1
    csv_path: /workspace/4D-Diff-RNA_test_1/Test_data/test_processing/rna_metadata_debug.csv
    eval_batch_size: 1
    filtering:
      max_len: 1000
      min_len: 1
    max_batch_size: 2
    max_num_res_squared: 375000
    max_squared_res: 375000
    min_t: 0.01
    num_eval_lengths: 10
    num_workers: 1
    prefetch_factor: 100
    samples_per_eval_length: 1
  experiment: !!python/object:__main__.ExperimentConfig
    batch_ot: !!python/object:__main__.BatchOTConfig
      cost: kabsch
      enabled: true
      noise_per_sample: 1
      permute: false
    checkpointer: !!python/object:__main__.CheckpointerConfig
      dirpath: ckpt/se3-fm/rna-frameflow/
      every_n_epochs: 40
      mode: min
      monitor: train/loss
      save_last: true
      save_top_k: 3
    debug: true
    num_devices: 1
    optimizer: !!python/object:__main__.OptimizerConfig
      lr: 0.0001
    seed: 123
    trainer: !!python/object:__main__.TrainerConfig
      accelerator: gpu
      accumulate_grad_batches: 1
      check_val_every_n_epoch: 20
      deterministic: false
      log_every_n_steps: 1
      max_epochs: 200
      min_epochs: 1
      overfit_batches: 0
      strategy: ddp
    training: !!python/object:__main__.TrainingConfig
      aux_loss_t_pass: 0.25
      aux_loss_weight: 1.0
      bb_atom_scale: 0.1
      loss: se3_vf_loss
      min_plddt_mask: null
      num_non_frame_atoms: 0
      rotation_loss_weights: 1.0
      t_normalize_clip: 0.9
      tors_loss_scale: 1.0
      trans_scale: 0.1
      translation_loss_weight: 2.0
    use_swa: false
    wandb: !!python/object:__main__.WandbConfig
      mode: online
      name: rna-frameflow
      project: se3-fm
      save_code: false
      tags: []
    warm_start: null
    warm_start_cfg_override: true
  interpolant: !!python/object:__main__.InterpolantConfig
    min_t: 0.01
    rots: !!python/object:__main__.rot_config
      exp_rate: 10
      sample_schedule: exp
      train_schedule: linear
    sampling: !!python/object:__main__.SamplingConfig
      num_timesteps: 50
    self_condition: true
    trans: !!python/object:__main__.trans_config
      sample_schedule: linear
      train_schedule: linear
  model: !!python/object:__main__.ModelConfig
    edge_embed_size: 128
    edge_features: !!python/object:__main__.EdgeFeaturesConfig
      c_p: 128
      c_s: 256
      feat_dim: 64
      num_bins: 22
      num_rbf: 32
      relpos_k: 64
      self_condition: true
      single_bias_transition_n: 2
      use_rbf: true
    ipa: !!python/object:__main__.IPAConfig
      c_hidden: 128
      c_s: 256
      c_z: 128
      no_heads: 8
      no_qk_points: 8
      no_v_points: 12
      num_blocks: 6
      seq_tfmr_num_heads: 4
      seq_tfmr_num_layers: 2
    node_embed_size: 256
    node_features: !!python/object:__main__.NodeFeaturesConfig
      c_pos_emb: 128
      c_s: 256
      c_timestep_emb: 128
      embed_diffuse_mask: false
      max_num_res: 2000
      timestep_int: 1000
    symmetric: false
folding_cfg: null
